import type { Article, Agency, Company, Founder, UserProfile, Category } from "./types"

export const CATEGORIES: { label: string; value: Category | "All" }[] = [
  { label: "All", value: "All" },
  { label: "AI", value: "AI" },
  { label: "Market", value: "Market" },
  { label: "Launches", value: "Launches" },
  { label: "Apps", value: "Apps" },
  { label: "Startups", value: "Startups" },
  { label: "Products", value: "Products" },
]

export const CATEGORY_COLORS: Record<string, string> = {
  AI: "#8B5CF6",
  Market: "#10B981",
  Launches: "#F59E0B",
  Apps: "#3B82F6",
  Startups: "#EF4444",
  Products: "#EC4899",
}

export const mockAgencies: Agency[] = [
  { id: "a1", name: "TechCrunch", slug: "techcrunch", logoUrl: "https://logo.clearbit.com/techcrunch.com", websiteUrl: "https://techcrunch.com", rssUrl: "", isTrusted: true, categoryFocus: ["Startups", "AI"], followerCount: 24500 },
  { id: "a2", name: "The Verge", slug: "the-verge", logoUrl: "https://logo.clearbit.com/theverge.com", websiteUrl: "https://theverge.com", rssUrl: "", isTrusted: true, categoryFocus: ["Products", "Apps"], followerCount: 18200 },
  { id: "a3", name: "Wired", slug: "wired", logoUrl: "https://logo.clearbit.com/wired.com", websiteUrl: "https://wired.com", rssUrl: "", isTrusted: true, categoryFocus: ["AI", "Market"], followerCount: 15800 },
  { id: "a4", name: "Ars Technica", slug: "ars-technica", logoUrl: "https://logo.clearbit.com/arstechnica.com", websiteUrl: "https://arstechnica.com", rssUrl: "", isTrusted: true, categoryFocus: ["AI", "Products"], followerCount: 12400 },
  { id: "a5", name: "VentureBeat", slug: "venturebeat", logoUrl: "https://logo.clearbit.com/venturebeat.com", websiteUrl: "https://venturebeat.com", rssUrl: "", isTrusted: true, categoryFocus: ["AI", "Startups"], followerCount: 9800 },
  { id: "a6", name: "MIT Tech Review", slug: "mit-tech-review", logoUrl: "https://logo.clearbit.com/technologyreview.com", websiteUrl: "https://technologyreview.com", rssUrl: "", isTrusted: true, categoryFocus: ["AI"], followerCount: 11200 },
  { id: "a7", name: "Product Hunt", slug: "product-hunt", logoUrl: "https://logo.clearbit.com/producthunt.com", websiteUrl: "https://producthunt.com", rssUrl: "", isTrusted: true, categoryFocus: ["Launches", "Products"], followerCount: 22100 },
  { id: "a8", name: "Engadget", slug: "engadget", logoUrl: "https://logo.clearbit.com/engadget.com", websiteUrl: "https://engadget.com", rssUrl: "", isTrusted: true, categoryFocus: ["Products", "Apps"], followerCount: 8700 },
]

export const mockCompanies: Company[] = [
  { id: "c1", name: "OpenAI", slug: "openai", logoUrl: "https://logo.clearbit.com/openai.com", description: "Creator of ChatGPT, GPT-4, and DALL-E. Leading AI research lab pushing the frontier of artificial general intelligence.", websiteUrl: "https://openai.com", rssFeedUrl: null, twitterHandle: "@OpenAI", foundedYear: 2015, category: "AI", followerCount: 45200 },
  { id: "c2", name: "Anthropic", slug: "anthropic", logoUrl: "https://logo.clearbit.com/anthropic.com", description: "AI safety company building reliable, interpretable AI systems including Claude.", websiteUrl: "https://anthropic.com", rssFeedUrl: null, twitterHandle: "@AnthropicAI", foundedYear: 2021, category: "AI", followerCount: 28400 },
  { id: "c3", name: "Apple", slug: "apple", logoUrl: "https://logo.clearbit.com/apple.com", description: "Technology giant known for iPhone, Mac, and services ecosystem.", websiteUrl: "https://apple.com", rssFeedUrl: null, twitterHandle: "@Apple", foundedYear: 1976, category: "Products", followerCount: 67800 },
  { id: "c4", name: "Google", slug: "google", logoUrl: "https://logo.clearbit.com/google.com", description: "Multinational tech company specializing in search, cloud, AI, and consumer electronics.", websiteUrl: "https://google.com", rssFeedUrl: null, twitterHandle: "@Google", foundedYear: 1998, category: "AI", followerCount: 54100 },
  { id: "c5", name: "Tesla", slug: "tesla", logoUrl: "https://logo.clearbit.com/tesla.com", description: "Electric vehicle and clean energy company pushing sustainable transport.", websiteUrl: "https://tesla.com", rssFeedUrl: null, twitterHandle: "@Tesla", foundedYear: 2003, category: "Market", followerCount: 38700 },
  { id: "c6", name: "Meta", slug: "meta", logoUrl: "https://logo.clearbit.com/meta.com", description: "Social technology company building the metaverse, AR/VR, and AI.", websiteUrl: "https://meta.com", rssFeedUrl: null, twitterHandle: "@Meta", foundedYear: 2004, category: "AI", followerCount: 31200 },
]

export const mockFounders: Founder[] = [
  { id: "f1", name: "Sam Altman", companyId: "c1", title: "CEO", avatarUrl: "https://pbs.twimg.com/profile_images/804990434455887872/BG0Xh7Oa_400x400.jpg", twitterHandle: "@sama", bio: "CEO of OpenAI. Previously president of Y Combinator.", latestQuote: "AI will be the most transformative technology humanity has ever built.", latestQuoteSource: "TechCrunch Interview", followerCount: 32100 },
  { id: "f2", name: "Dario Amodei", companyId: "c2", title: "CEO & Co-Founder", avatarUrl: "https://pbs.twimg.com/profile_images/1657845002422226944/MAWTOd8h_400x400.jpg", twitterHandle: "@DarioAmodei", bio: "CEO of Anthropic. Former VP of Research at OpenAI.", latestQuote: "Safety and capability are not at odds with each other.", latestQuoteSource: "Wired Profile", followerCount: 18900 },
  { id: "f3", name: "Tim Cook", companyId: "c3", title: "CEO", avatarUrl: "https://pbs.twimg.com/profile_images/1535420431766671360/Pwq-1eJc_400x400.jpg", twitterHandle: "@tim_cook", bio: "CEO of Apple. Joined Apple in 1998 and became CEO in 2011.", latestQuote: "We believe privacy is a fundamental human right.", latestQuoteSource: "WWDC 2025", followerCount: 29400 },
  { id: "f4", name: "Sundar Pichai", companyId: "c4", title: "CEO", avatarUrl: "https://pbs.twimg.com/profile_images/864282616597405701/M-FEJMZ0_400x400.jpg", twitterHandle: "@sundarpichai", bio: "CEO of Alphabet and Google.", latestQuote: "AI is the most profound technology we are working on today.", latestQuoteSource: "Google I/O 2025", followerCount: 26800 },
  { id: "f5", name: "Elon Musk", companyId: "c5", title: "CEO", avatarUrl: "https://pbs.twimg.com/profile_images/1845482317555552256/OT9FCBWI_400x400.jpg", twitterHandle: "@elonmusk", bio: "CEO of Tesla and SpaceX. Owner of X.", latestQuote: "The pace of AI improvement is staggering.", latestQuoteSource: "X Post", followerCount: 55300 },
  { id: "f6", name: "Mark Zuckerberg", companyId: "c6", title: "CEO & Founder", avatarUrl: "https://pbs.twimg.com/profile_images/77846223/profile_400x400.jpg", twitterHandle: "@faborig", bio: "CEO and founder of Meta.", latestQuote: "Open source AI will be the most important trend of this decade.", latestQuoteSource: "Meta Connect", followerCount: 24600 },
]

export const mockArticles: Article[] = [
  {
    id: "art-1",
    title: "OpenAI Unveils GPT-5 with Breakthrough Reasoning Capabilities",
    summary: "OpenAI has released GPT-5, its most powerful model yet, featuring advanced reasoning, multimodal understanding, and real-time web access. The model shows significant improvements in coding, math, and creative tasks.",
    originalUrl: "https://techcrunch.com/2026/03/openai-gpt5",
    sourceName: "TechCrunch",
    sourceLogoUrl: "https://logo.clearbit.com/techcrunch.com",
    sourceAgencyId: "a1",
    publishedAt: new Date(Date.now() - 12 * 60000).toISOString(),
    fetchedAt: new Date(Date.now() - 10 * 60000).toISOString(),
    category: "AI",
    tags: ["OpenAI", "GPT-5", "LLM", "Artificial Intelligence"],
    isVerifiedSource: true,
    companyId: "c1",
    founderId: "f1",
    imageUrl: "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800&q=80",
    viewCount: 14520,
  },
  {
    id: "art-2",
    title: "Apple Announces iOS 27 with Revolutionary On-Device AI",
    summary: "Apple revealed iOS 27 at WWDC, featuring a fully on-device AI assistant that processes requests locally. Privacy-first approach means no data leaves the device while delivering GPT-level intelligence.",
    originalUrl: "https://theverge.com/2026/03/apple-ios-27",
    sourceName: "The Verge",
    sourceLogoUrl: "https://logo.clearbit.com/theverge.com",
    sourceAgencyId: "a2",
    publishedAt: new Date(Date.now() - 45 * 60000).toISOString(),
    fetchedAt: new Date(Date.now() - 40 * 60000).toISOString(),
    category: "Launches",
    tags: ["Apple", "iOS", "On-Device AI", "WWDC"],
    isVerifiedSource: true,
    companyId: "c3",
    founderId: "f3",
    imageUrl: "https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=800&q=80",
    viewCount: 9830,
  },
  {
    id: "art-3",
    title: "Tech Stocks Surge as AI Spending Shows No Signs of Slowing",
    summary: "The Nasdaq hit an all-time high as major tech companies reported record AI infrastructure spending. Analysts project the AI market to exceed $2 trillion by 2028.",
    originalUrl: "https://wired.com/2026/03/tech-stocks-ai",
    sourceName: "Wired",
    sourceLogoUrl: "https://logo.clearbit.com/wired.com",
    sourceAgencyId: "a3",
    publishedAt: new Date(Date.now() - 90 * 60000).toISOString(),
    fetchedAt: new Date(Date.now() - 85 * 60000).toISOString(),
    category: "Market",
    tags: ["Stocks", "AI Market", "Nasdaq", "Investment"],
    isVerifiedSource: true,
    companyId: null,
    founderId: null,
    imageUrl: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=800&q=80",
    viewCount: 7640,
  },
  {
    id: "art-4",
    title: "Anthropic Launches Claude 4 Opus with 500K Token Context",
    summary: "Anthropic's Claude 4 Opus pushes the boundary with a massive 500K token context window, improved coding abilities, and new tool-use capabilities that rival human assistants.",
    originalUrl: "https://venturebeat.com/2026/03/claude-4-opus",
    sourceName: "VentureBeat",
    sourceLogoUrl: "https://logo.clearbit.com/venturebeat.com",
    sourceAgencyId: "a5",
    publishedAt: new Date(Date.now() - 120 * 60000).toISOString(),
    fetchedAt: new Date(Date.now() - 115 * 60000).toISOString(),
    category: "AI",
    tags: ["Anthropic", "Claude", "LLM", "Context Window"],
    isVerifiedSource: true,
    companyId: "c2",
    founderId: "f2",
    imageUrl: "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=800&q=80",
    viewCount: 6210,
  },
  {
    id: "art-5",
    title: "Google DeepMind Achieves Breakthrough in Protein Drug Discovery",
    summary: "DeepMind's AlphaFold 4 has successfully predicted drug-protein interactions with 98% accuracy, potentially revolutionizing pharmaceutical development and cutting drug discovery time by years.",
    originalUrl: "https://technologyreview.com/2026/03/deepmind-drug",
    sourceName: "MIT Tech Review",
    sourceLogoUrl: "https://logo.clearbit.com/technologyreview.com",
    sourceAgencyId: "a6",
    publishedAt: new Date(Date.now() - 150 * 60000).toISOString(),
    fetchedAt: new Date(Date.now() - 145 * 60000).toISOString(),
    category: "AI",
    tags: ["DeepMind", "AlphaFold", "Drug Discovery", "Healthcare"],
    isVerifiedSource: true,
    companyId: "c4",
    founderId: "f4",
    imageUrl: "https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=800&q=80",
    viewCount: 5100,
  },
  {
    id: "art-6",
    title: "YC-Backed Startup Raises $120M to Build AI-Powered Legal Tools",
    summary: "Harvey AI, the Y Combinator-backed legal AI startup, closed a $120M Series B round led by Sequoia Capital. The company aims to automate 80% of routine legal work.",
    originalUrl: "https://techcrunch.com/2026/03/harvey-ai-funding",
    sourceName: "TechCrunch",
    sourceLogoUrl: "https://logo.clearbit.com/techcrunch.com",
    sourceAgencyId: "a1",
    publishedAt: new Date(Date.now() - 180 * 60000).toISOString(),
    fetchedAt: new Date(Date.now() - 175 * 60000).toISOString(),
    category: "Startups",
    tags: ["YC", "Legal Tech", "Series B", "AI Startup"],
    isVerifiedSource: true,
    companyId: null,
    founderId: null,
    imageUrl: "https://images.unsplash.com/photo-1551434678-e076c223a692?w=800&q=80",
    viewCount: 4300,
  },
  {
    id: "art-7",
    title: "Meta Releases Llama 5 Open Source, Biggest Open AI Model Yet",
    summary: "Meta has open-sourced Llama 5 with 400B parameters, making it the largest openly available AI model. Early benchmarks show it competing with GPT-5 on several tasks.",
    originalUrl: "https://arstechnica.com/2026/03/meta-llama-5",
    sourceName: "Ars Technica",
    sourceLogoUrl: "https://logo.clearbit.com/arstechnica.com",
    sourceAgencyId: "a4",
    publishedAt: new Date(Date.now() - 200 * 60000).toISOString(),
    fetchedAt: new Date(Date.now() - 195 * 60000).toISOString(),
    category: "AI",
    tags: ["Meta", "Llama", "Open Source", "LLM"],
    isVerifiedSource: true,
    companyId: "c6",
    founderId: "f6",
    imageUrl: "https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=800&q=80",
    viewCount: 8900,
  },
  {
    id: "art-8",
    title: "New Productivity App 'Flow' Tops App Store Charts in 24 Hours",
    summary: "Flow, a minimalist task management app with AI scheduling, hit #1 on the App Store within 24 hours of launch. Its unique approach to time-blocking has resonated with remote workers.",
    originalUrl: "https://producthunt.com/2026/03/flow-app",
    sourceName: "Product Hunt",
    sourceLogoUrl: "https://logo.clearbit.com/producthunt.com",
    sourceAgencyId: "a7",
    publishedAt: new Date(Date.now() - 240 * 60000).toISOString(),
    fetchedAt: new Date(Date.now() - 235 * 60000).toISOString(),
    category: "Apps",
    tags: ["Productivity", "App Store", "AI Scheduling"],
    isVerifiedSource: true,
    companyId: null,
    founderId: null,
    imageUrl: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=800&q=80",
    viewCount: 3700,
  },
  {
    id: "art-9",
    title: "Tesla Unveils Optimus Gen 3 Robot with Human-Level Dexterity",
    summary: "Tesla demonstrated its third-generation Optimus humanoid robot performing complex tasks including cooking and folding laundry with unprecedented precision.",
    originalUrl: "https://engadget.com/2026/03/tesla-optimus-gen3",
    sourceName: "Engadget",
    sourceLogoUrl: "https://logo.clearbit.com/engadget.com",
    sourceAgencyId: "a8",
    publishedAt: new Date(Date.now() - 300 * 60000).toISOString(),
    fetchedAt: new Date(Date.now() - 295 * 60000).toISOString(),
    category: "Products",
    tags: ["Tesla", "Robotics", "Optimus", "Hardware"],
    isVerifiedSource: true,
    companyId: "c5",
    founderId: "f5",
    imageUrl: "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=800&q=80",
    viewCount: 11200,
  },
  {
    id: "art-10",
    title: "EU Passes Landmark AI Transparency Act Requiring Model Disclosure",
    summary: "The European Union has passed sweeping legislation requiring all AI companies to disclose training data sources, model architecture details, and safety testing results.",
    originalUrl: "https://wired.com/2026/03/eu-ai-transparency",
    sourceName: "Wired",
    sourceLogoUrl: "https://logo.clearbit.com/wired.com",
    sourceAgencyId: "a3",
    publishedAt: new Date(Date.now() - 360 * 60000).toISOString(),
    fetchedAt: new Date(Date.now() - 355 * 60000).toISOString(),
    category: "Market",
    tags: ["EU", "Regulation", "AI Policy", "Transparency"],
    isVerifiedSource: true,
    companyId: null,
    founderId: null,
    imageUrl: "https://images.unsplash.com/photo-1529107386315-e1a2ed48a620?w=800&q=80",
    viewCount: 5800,
  },
]

export const mockUser: UserProfile = {
  uid: "user-001",
  email: "alex@example.com",
  displayName: "Alex Chen",
  photoURL: "",
  plan: "free",
  newsletterSubscribed: true,
  articlesRead: 142,
  articlesSaved: 23,
  topicsFollowed: 8,
  memberSince: "2025-09-15",
}

export const mockSavedArticleIds = ["art-1", "art-4", "art-7"]

export const trendingTopics = [
  { name: "GPT-5", viewCount: 142000, imageUrl: "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=300&q=80" },
  { name: "Apple WWDC", viewCount: 98000, imageUrl: "https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=300&q=80" },
  { name: "Llama 5", viewCount: 87000, imageUrl: "https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=300&q=80" },
  { name: "AI Regulation", viewCount: 65000, imageUrl: "https://images.unsplash.com/photo-1529107386315-e1a2ed48a620?w=300&q=80" },
  { name: "Robotics", viewCount: 54000, imageUrl: "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=300&q=80" },
  { name: "Drug Discovery", viewCount: 43000, imageUrl: "https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=300&q=80" },
]
